/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ast2.glb
Author: Ignazio Pillitteri (https://sketchfab.com/gnaz)
License: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
Source: https://sketchfab.com/3d-models/asteroid-ceres-f57c49e7eb90439c97064d2ddea09d25
Title: Asteroid: Ceres
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ast2(props) {
  const { nodes, materials } = useGLTF('/models/n1/ast2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.488, 0, -1.309]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.006}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Default_OBJ} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Default_OBJ} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/n1/ast2.glb')
