/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 n1.glb
Author: ImADefaultCube117 (https://sketchfab.com/20193dd085)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/the-mandalorian-ship-starfighter-n1-29b17c10beef48ddb868c2ae7c4374df
Title: The mandalorian Ship - Starfighter N1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function N1(props) {
  const { nodes, materials } = useGLTF('/models/n1/n1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Turbinas} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Turbinas} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Turbinas} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.317, 0.051, 0.232]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.MotorT} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} />
      </group>
      <group scale={0.827}>
        <mesh geometry={nodes.Object_15.geometry} material={materials.Carroceria} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.005']} />
      </group>
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Armas} />
    </group>
  )
}

useGLTF.preload('/models/n1/n1.glb')
